parameters:
    tmdb.api_key: '%env(resolve:TMDB_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TmdbApiService:
        arguments:
            $apiKey: '%tmdb.api_key%'
            $params: '@parameter_bag'